BradkenProduction/force-app/main/default/objects/Manufacturing_Facility__c/Manufacturing_Facility__c.object-meta.xml
<CustomObject>
    <description>Manufacturing Facilities and mapping to its facility manager</description>
    <label>Manufacturing Supplier</label>
    <nameField>
        <label>Suppplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Suppliers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/Quote_Facility__c.object-meta.xml
<CustomObject>
    <description>Facilities selected on a Quote</description>
    <label>Quote Supplier</label>
    <nameField>
        <displayFormat>QF-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Manufacturing_Facility__c</referenceTo>
    <relationshipName>Quote_Facilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>Quote Name/Number</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Quote_Facilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Quote Line Items to be used in Supplier Selection/Freight Quote Request Cases</description>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Quote_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

BradkenProduction/force-app/main/default/classes/EclSelectionControllerTest.cls
@isTest
public with sharing class EclSelectionControllerTest {
    static final Integer numberRecords = 10;
	static List<String> ids;

	static{
		Account testAcc = new Account(Name = 'testAcc');
		insert testAcc;
		Product2 testProduct = new Product2(Name = 'testProduct', isActive = true);
		insert testProduct;
		Pricebook2 pb = new Pricebook2(Name = 'testPriceBook', IsActive = true );
        insert pb;
		PriceBookEntry testPBE = new PriceBookEntry(UnitPrice = 300, PriceBook2Id = Test.getStandardPricebookId(),
                                                        Product2Id = testProduct.Id, IsActive = true);
        insert testPBE;
		Opportunity testOpp = new Opportunity(Name = 'testOpp', AccountId = testAcc.Id, StageName = 'New', CloseDate = Date.today()+1);
        insert testOpp;
		Quote testQuote = new Quote(OpportunityId = testOpp.Id, Name = 'testQuote', Pricebook2Id = Test.getStandardPricebookId(), Status = 'New' , Named_Place__c='Test' ,Inco_Term__c ='CFR');
        insert testQuote;
		List<Manufacturing_Facility__c> testListManufacturingFacilites = new List<Manufacturing_Facility__c>();
		for(Integer i = 0; i < numberRecords; i++) {
			testListManufacturingFacilites.add(new Manufacturing_Facility__c(
				Name = 'testMF' + i
			));
		}
		insert testListManufacturingFacilites;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = testOpp.id, Quantity = 1, PricebookEntryId = testPBE.Id, totalPrice = 200);
       insert oli;

		QuoteLineItem qli = new QuoteLineItem(QuoteId = testQuote.Id, PriceBookentryId = testPBE.Id, Quantity = 1, UnitPrice = 1, Product2Id = testProduct.Id);
		System.debug('qli.Product2Id' + qli.Product2Id);
		System.debug('qli.Product2.IsActive' + qli.Product2.IsActive);
    	insert qli; 

		// QuoteLineItem testQuoteLineItem = new QuoteLineItem(QuoteId= testQuote.Id, PricebookEntryId = testPBE.Id, Quantity = 10, UnitPrice = 300, Product2Id = testProduct.Id);
		// insert testQuoteLineItem;


		List<Quote_Facility__c> testListQuoteFacilites = new List<Quote_Facility__c>();
		for(Integer i = 0; i < numberRecords; i++) {
			testListQuoteFacilites.add(new Quote_Facility__c(
				Quote__c = testQuote.Id,
				Facility__c = testListManufacturingFacilites.get(i).Id,
				Quote_Line_Item__c = qli.Id
			));
		}
		insert testListQuoteFacilites;
		List<String> quoteIds = new List<String>();
		for(Quote_Facility__c q : testListQuoteFacilites) {
			quoteIds.add(q.Id);
		}
		ids = quoteIds;
		
	}

	@isTest
	public static void testGetQuoteFacility() {
		Test.startTest();
		List<Quote_Facility__c> result = EclSelectionController.getQuoteFacility(ids);
		Test.stopTest();
		System.assertEquals(numberRecords, result.size());
	}
	
	@isTest
	public static void testGetQuoteFacilityFromFlow() {
		Test.startTest();
		List<Boolean> result = EclSelectionController.getQuoteFacilityFromFlow(ids);
		Test.stopTest();
		System.assertEquals(result.get(0),true);
	}
}