BradkenProduction/force-app/main/default/objects/Customer_Purchase_Order__c/Customer_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>To maintain record of Purchase Orders received</description>
    <label>Customer Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Customer_Purchase_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer Name</description>
    <inlineHelpText>Customer</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Purchase Orders</relationshipLabel>
    <relationshipName>Customer_Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Customer_Purchase_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity against which the Purchase order is received</description>
    <inlineHelpText>The Opportunity against which this PO is received</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Purchase Orders</relationshipLabel>
    <relationshipName>Customer_Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Contains Products added to a Purchase Order</description>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PO Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity of the Product Ordered</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

BradkenProduction/force-app/main/default/classes/PurchaseOrderControllerTest.cls
/**
* @author: Tquila dev
* @Used for: test class for PurchaseOrderController components 
* @TestClass: PurchaseOrderControllerTest
* @History : 
*/ 
@isTest
public class PurchaseOrderControllerTest {
	@testSetup
    public static void insertTestRecords(){
        TestService.createTestData();
        TestService.createOpportunityLineItem([select id,Pricebook2Id from opportunity limit 1]);
        //Create a test user
        //TestService.createTestUser(TestService.testUsername,TestService.testProfileName );
        
    }
    
    public static testmethod void getOpportunityLinesTest(){
        string recordId = [select id,Pricebook2Id from opportunity limit 1].id;
        test.startTest();
            list<OpportunityLineItem> olis = PurchaseOrderController.getOpportunityLines(recordId);
            system.assert(!olis.isEmpty());
		test.stopTest();
    }
    
    public static testmethod void insertRecordsTest(){
        
        boolean isSuccess = true;
        try{
            test.startTest();
            Customer_Purchase_Order__c cpo = new Customer_Purchase_Order__c();
            cpo.Account__c = [select id from Account limit 1].Id;
            cpo.Opportunity__c = [select id from Opportunity limit 1].Id;
            cpo.Name = '123';
            list<Purchase_Order_Line_Item__c> purchaseOrderLines = new list<Purchase_Order_Line_Item__c>();
            list<OpportunityLineItem> olis = PurchaseOrderController.getOpportunityLines(cpo.Opportunity__c);
            
            for(OpportunityLineItem oli : olis){
                Purchase_Order_Line_Item__c pol = new Purchase_Order_Line_Item__c();
                pol.Quantity__c = 1;
                purchaseOrderLines.add(pol);
            }
            String res = PurchaseOrderController.insertRecords(cpo,purchaseOrderLines,olis);
            system.assert(res == 'ok');
            string s = PurchaseOrderController.getOpportunityProductFieldsToCopy();
            test.stopTest();
            res = PurchaseOrderController.insertRecords(null,null,null);
        }catch(Exception e){
            isSuccess = false;
        }
		system.assert(!isSuccess);
		
    }

}