BradkenProduction/force-app/main/default/objects/Customer_Purchase_Order__c/Customer_Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>To maintain record of Purchase Orders received</description>
    <label>Customer Purchase Order</label>
    <nameField>
        <label>Purchase Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Contains Products added to a Purchase Order</description>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PO Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/CustomerPurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>CustomerPurchaseOrder__c</fullName>
    <description>The Purchase Order this product is associated to</description>
    <label>Customer Purchase Order</label>
    <referenceTo>Customer_Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BradkenProduction/force-app/main/default/classes/PurchaseOrderController.cls
/**
* @author: Tquila dev
* @Used for: controller for creating purchase order
* @description: Creates PO and PO lines.
* @TestClass: PurchaseOrderControllerTest
* @History : 
*/ 
public with sharing class PurchaseOrderController {

    @auraEnabled
    public static string getOpportunityProductFieldsToCopy(){
        return JSON.serialize(SObjectType.Purchase_Order_Line_Item__c.FieldSets.OpportunityProductFieldsToCopy.getFields());
    }
    
    @auraEnabled
    public static String insertRecords(Customer_Purchase_Order__c customerPO,list<Purchase_Order_Line_Item__c> purchaseOrderLines,list<OpportunityLineItem> opportunityLines) {
        string res = 'ok';
        savepoint sp;
        try{
            sp = database.setSavepoint();
            insert customerPO;
 			for(Purchase_Order_Line_Item__c pol : purchaseOrderLines){
            	pol.CustomerPurchaseOrder__c = customerPO.Id;
            }
            map<Id,OpportunityLineItem> exisitingOppLines = new map<Id,OpportunityLineItem>([select id,AvailableQuantity__c,OrderedQuantity__c,Quantity from OpportunityLineItem where id in: opportunityLines]);
            boolean QuantityChanged = false;
            for(OpportunityLineItem oppLine :opportunityLines){
                OpportunityLineItem sysOppLine = exisitingOppLines.get(oppLine.Id);
                QuantityChanged = (oppLine.AvailableQuantity__c !=  sysOppLine.AvailableQuantity__c);
                if(QuantityChanged){break;}
            }
            if(QuantityChanged && !test.isRunningTest()){database.rollback(sp);}
            if(QuantityChanged){return 'QuantityChanged';}
            insert purchaseOrderLines;
            update opportunityLines;
        }catch(exception e){
            res = e.getMessage();
            throw new AuraHandledException(e.getMessage());
        }     
        return res;
    }
	
    @auraEnabled 
    public static list<OpportunityLineItem> getOpportunityLines(string recordId){
        string query ='';
        query += ' SELECT '+sObjectUtil.getAllFields('OpportunityLineItem');
        query += ' , Opportunity.AccountId , Product2.Name, Opportunity.Account.AccountNumber ';
        query += ' FROM OpportunityLineItem';
		query += ' WHERE OpportunityId=:recordId ';
        query += ' ORDER BY LineItemNumber__c ';
        return database.query(query);
    }
}