BradkenProduction/force-app/main/default/objects/Quote_Facility__c/Quote_Facility__c.object-meta.xml
<CustomObject>
    <description>Facilities selected on a Quote</description>
    <label>Quote Supplier</label>
    <nameField>
        <displayFormat>QF-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Bradken_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Bradken_Part_Number__c</fullName>
    <description>Bradken Part Number from the associated Quote Line Item</description>
    <formula>Quote_Line_Item__r.Bradken_Part_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bradken Part Number</label>
    <type>Text</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/ECL_Supplier_Grouping__c.field-meta.xml
<CustomField>
    <fullName>ECL_Supplier_Grouping__c</fullName>
    <description>Title given to selected suppliers that will be used in the ECL process to determine which products to send</description>
    <inlineHelpText>Title given to selected suppliers that will be used in the ECL process to determine which products to send</inlineHelpText>
    <label>ECL Supplier Grouping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Manufacturing_Facility__c</referenceTo>
    <relationshipName>Quote_Facilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <formula>Facility__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Name</label>
    <type>Text</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <description>Populated by Nintex Workflow ECL Form</description>
    <inlineHelpText>Lead time to supply the product from the corresponding facility</inlineHelpText>
    <label>Lead Time</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Product_Cost__c.field-meta.xml
<CustomField>
    <fullName>Product_Cost__c</fullName>
    <description>Populated by Nintex Workflow ECL Form</description>
    <inlineHelpText>Facility cost price</inlineHelpText>
    <label>Product Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BradkenProduction/force-app/main/default/objects/Quote_Facility__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Quote Line Items to be used in Supplier Selection/Freight Quote Request Cases</description>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Quote_Facilities</relationshipName>
    <type>Lookup</type>
</CustomField>

BradkenProduction/force-app/main/default/classes/EclSelectionController.cls
public with sharing class EclSelectionController {
	@AuraEnabled
    public static List<Quote_Facility__c> getQuoteFacility(List<String> incomingIds) {
		return [
			SELECT Id, Name, Facility_Name__c, Lead_Time__c, Product_Cost__c, Bradken_Part_Number__c, ECL_Supplier_Grouping__c,Quote_Line_Item__r.LineNumber
			FROM Quote_Facility__c
			WHERE Id IN :incomingIds
		];
	}

	@InvocableMethod(label= 'Check if there are one parent facility.')
    public static List<Boolean> getQuoteFacilityFromFlow(List<String> ids) {
		List<String> incomingIds = ids.get(0).split(',');
		List<Quote_Facility__c> selectedQuoteFacilities =  [
			SELECT Id, Facility__c, Quote_Line_Item__c
			FROM Quote_Facility__c
			WHERE Id IN :incomingIds
		];
		Set<Id> usedQuoteLineItems = new Set<Id>();

		for(Quote_Facility__c qf : selectedQuoteFacilities) {
			if(qf.Quote_Line_Item__c == null || qf.Facility__c == null) {
				return new List<Boolean>{false};
			}
			usedQuoteLineItems.add(qf.Facility__c);
		}
		if(usedQuoteLineItems.size() == 1) {
			return new List<Boolean>{true};
		}
		return new List<Boolean>{false};
		
	}

}